package View;
import Controller.AdminController;
import Model.ModelCustomer;
import java.util.ArrayList;
import Controller.CustomerController;
import Controller.TransactionController;
import Model.ModelTransaksi;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        AdminController adminController = new AdminController();
        adminController.updateUsernameLabel(LabelUsername, Login.adminId);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LabelDataPelanggan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataPelanggan = new javax.swing.JTable();
        buttonTambahPelanggan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        LabelDataTransaksi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransactionController transactionController = new TransactionController();

        ArrayList<ModelTransaksi> listTransaksi;
        listTransaksi = transactionController.getTransactionData();

        ArrayList<ModelTransaksi> listTransaksiSesuaiAdmin;
        listTransaksiSesuaiAdmin = transactionController.getTransactionDataSesuaiAdmin(listTransaksi,Login.adminId);
        Object[][] ObjectTransaksi = new Object[listTransaksiSesuaiAdmin.size()][9];

        for (int i=0; i<listTransaksiSesuaiAdmin.size();i++){
            for (int j=0;j<9;j++){
                if (j==0){
                    ObjectTransaksi[i][j] = i+1;
                }else if (j==1){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getIdCustomer();
                }else if (j==2){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getLayanan();
                }else if (j==3){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getStatus();
                }else if (j==4){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getTgl();
                }else if (j==5){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getItem();
                }else if (j==6){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getHargaPerKg();
                }else if (j==7){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getBerat();
                }else if (j==8){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getTotal();
                }
            }
            //}
    }
    TabelDataTransaksi = new javax.swing.JTable();
    buttonTambahTransaksi = new javax.swing.JButton();
    buttonUpdateTransaksi = new javax.swing.JButton();
    buttonDeleteTransaksi = new javax.swing.JButton();
    LabelWlcome = new javax.swing.JLabel();
    LabelUsername = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(0, 0, 0));

    buttonLogout.setBackground(new java.awt.Color(48, 48, 48));
    buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
    buttonLogout.setText("Logout");
    buttonLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    buttonLogout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonLogoutActionPerformed(evt);
        }
    });

    jPanel4.setBackground(new java.awt.Color(23, 23, 23));

    LabelDataPelanggan.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
    LabelDataPelanggan.setForeground(new java.awt.Color(255, 255, 255));
    LabelDataPelanggan.setText("Data Pelanggan");

    jScrollPane1.setBackground(new java.awt.Color(23, 23, 23));

    CustomerController customerController = new CustomerController();

    ArrayList<ModelCustomer> listCustomer;
    listCustomer = customerController.getCustomerData();
    ArrayList<ModelCustomer> listCustomerSesuaiAdmin;
    listCustomerSesuaiAdmin = customerController.getCustomerDataSesuaiAdmin(listCustomer, Login.adminId);
    Object[][] Object = new Object[listCustomerSesuaiAdmin.size()][4];
    for (int i=0; i<listCustomerSesuaiAdmin.size();i++){
        //System.out.println(listCustomer.get(i).getIdAdmin());
        //System.out.println(Login.adminId);
        //    if (listCustomer.get(i).getIdAdmin()== Login.adminId){
            //        System.out.println("Masuk data pelanggan");
            for (int j=0;j<4;j++){
                if (j==0){
                    Object[i][j] = listCustomerSesuaiAdmin.get(i).getIdCustomer();
                }else if (j==1){
                    Object[i][j] = listCustomerSesuaiAdmin.get(i).getNama();
                }else if (j==2){
                    Object[i][j] = listCustomerSesuaiAdmin.get(i).getAlamat();
                }else if (j==3){
                    Object[i][j] = listCustomerSesuaiAdmin.get(i).getNoTelp();
                }
            }
            //}
    }
    TabelDataPelanggan.setBackground(new java.awt.Color(255, 255, 255));
    TabelDataPelanggan.setForeground(new java.awt.Color(0, 0, 0));
    TabelDataPelanggan.setModel(new javax.swing.table.DefaultTableModel(
        Object,
        new String [] {
            "ID Pelanggan", "Nama Pelanggan", "Alamat Pelanggan", "no. Telp Pelanggan"
        }
    ));
    jScrollPane1.setViewportView(TabelDataPelanggan);

    buttonTambahPelanggan.setBackground(new java.awt.Color(48, 48, 48));
    buttonTambahPelanggan.setForeground(new java.awt.Color(255, 255, 255));
    buttonTambahPelanggan.setText("Tambah");
    buttonTambahPelanggan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    buttonTambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonTambahPelangganActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(LabelDataPelanggan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LabelDataPelanggan)
                .addComponent(buttonTambahPelanggan))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBackground(new java.awt.Color(23, 23, 23));

    LabelDataTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
    LabelDataTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    LabelDataTransaksi.setText("Data Transaksi");

    jScrollPane2.setBackground(new java.awt.Color(23, 23, 23));

    TabelDataTransaksi.setBackground(new java.awt.Color(255, 255, 255));
    TabelDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
        ObjectTransaksi,
        new String [] {
            "No", "ID Pelanggan", "Layanan Pencucian", "Status Pencucian", "Tanggal", "Item","Harga per Kg","Berat","Total Harga"
        }
    ));
    jScrollPane2.setViewportView(TabelDataTransaksi);

    buttonTambahTransaksi.setBackground(new java.awt.Color(48, 48, 48));
    buttonTambahTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    buttonTambahTransaksi.setText("Tambah");
    buttonTambahTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    buttonTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonTambahTransaksiActionPerformed(evt);
        }
    });

    buttonUpdateTransaksi.setBackground(new java.awt.Color(48, 48, 48));
    buttonUpdateTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    buttonUpdateTransaksi.setText("Update");
    buttonUpdateTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    buttonUpdateTransaksi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonUpdateTransaksiActionPerformed(evt);
        }
    });

    buttonDeleteTransaksi.setBackground(new java.awt.Color(48, 48, 48));
    buttonDeleteTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    buttonDeleteTransaksi.setText("Hapus");
    buttonDeleteTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    buttonDeleteTransaksi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonDeleteTransaksiActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(LabelDataTransaksi)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonUpdateTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonDeleteTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LabelDataTransaksi)
                .addComponent(buttonTambahTransaksi)
                .addComponent(buttonUpdateTransaksi)
                .addComponent(buttonDeleteTransaksi))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    LabelWlcome.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
    LabelWlcome.setForeground(new java.awt.Color(255, 255, 255));
    LabelWlcome.setText("Welcome,");

    LabelUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
    LabelUsername.setForeground(new java.awt.Color(255, 255, 255));
    LabelUsername.setText("[Username]");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(LabelWlcome)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LabelUsername)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(36, 36, 36))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addComponent(LabelUsername)
                .addComponent(LabelWlcome))
            .addGap(36, 36, 36)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(36, 36, 36))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahPelangganActionPerformed
        TambahPelanggan TP = new TambahPelanggan();
        setVisible(false);
        TP.setVisible(true);
    }//GEN-LAST:event_buttonTambahPelangganActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        Login L = new Login();
        setVisible(false);
        L.setVisible(true);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahTransaksiActionPerformed
        TambahTransaksi TT = new TambahTransaksi();
        setVisible(false);
        TT.setVisible(true);
    }//GEN-LAST:event_buttonTambahTransaksiActionPerformed

    private void buttonUpdateTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateTransaksiActionPerformed
        // TODO add your handling code here:
        TransactionController transactionController = new TransactionController();
        int i = TabelDataTransaksi.getSelectedRow();
        if (i!=-1){
            ArrayList<ModelTransaksi> listTransaksi;
            listTransaksi = transactionController.getTransactionData();
            ArrayList<ModelTransaksi> listTransaksiSesuaiAdmin;
            listTransaksiSesuaiAdmin = transactionController.getTransactionDataSesuaiAdmin(listTransaksi,Login.adminId);

            int idTransaksi = listTransaksiSesuaiAdmin.get(i).getIdTransaksi();
            UpdateTransaksi UT = new UpdateTransaksi(idTransaksi,i);
            setVisible(false);
            UT.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diupdate");
        }
        
    }//GEN-LAST:event_buttonUpdateTransaksiActionPerformed

    private void buttonDeleteTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTransaksiActionPerformed
        TransactionController transactionController = new TransactionController();
        
        int i = TabelDataTransaksi.getSelectedRow();  
        
        if (i!= -1){
            ArrayList<ModelTransaksi> listTransaksi;
            listTransaksi = transactionController.getTransactionData();
            ArrayList<ModelTransaksi> listTransaksiSesuaiAdmin;
            listTransaksiSesuaiAdmin = transactionController.getTransactionDataSesuaiAdmin(listTransaksi,Login.adminId);
            
            int idTransaksi = listTransaksiSesuaiAdmin.get(i).getIdTransaksi();
            DefaultTableModel tableModel = (DefaultTableModel) TabelDataTransaksi.getModel();
            transactionController.deleteTransaksi(idTransaksi);
            
            JOptionPane.showMessageDialog(null, "Transaksi Berhasil Dihapus");
            tableModel.removeRow(i);
            transactionController.updateRowNumbers(tableModel);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan dihapus");
        }
        
    }//GEN-LAST:event_buttonDeleteTransaksiActionPerformed
    public Object[][] getTransactionData() {
        TransactionController transactionController = new TransactionController();

        ArrayList<ModelTransaksi> listTransaksi;
        listTransaksi = transactionController.getTransactionData();

        ArrayList<ModelTransaksi> listTransaksiSesuaiAdmin;
        listTransaksiSesuaiAdmin = transactionController.getTransactionDataSesuaiAdmin(listTransaksi, Login.adminId);

        Object[][] ObjectTransaksi = new Object[listTransaksiSesuaiAdmin.size()][9];

        for (int i = 0; i < listTransaksiSesuaiAdmin.size(); i++) {
            for (int j = 0; j < 9; j++) {
                if (j==0){
                    ObjectTransaksi[i][j] = i+1;
                }else if (j==1){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getIdCustomer();
                }else if (j==2){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getLayanan();
                }else if (j==3){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getStatus();
                }else if (j==4){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getTgl();
                }else if (j==5){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getItem();
                }else if (j==6){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getHargaPerKg();
                }else if (j==7){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getBerat();
                }else if (j==8){
                    ObjectTransaksi[i][j] = listTransaksiSesuaiAdmin.get(i).getTotal();
                }
            }
        }

        return ObjectTransaksi;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDataPelanggan;
    private javax.swing.JLabel LabelDataTransaksi;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LabelWlcome;
    private javax.swing.JTable TabelDataPelanggan;
    private javax.swing.JTable TabelDataTransaksi;
    private javax.swing.JButton buttonDeleteTransaksi;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonTambahPelanggan;
    private javax.swing.JButton buttonTambahTransaksi;
    private javax.swing.JButton buttonUpdateTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
  
}
