package View;

import Controller.CustomerController;
import javax.swing.JOptionPane;

public class TambahPelanggan extends javax.swing.JFrame {
    public TambahPelanggan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelTambahDataPelanggan2 = new javax.swing.JLabel();
        LabelNama2 = new javax.swing.JLabel();
        LabelAlamat2 = new javax.swing.JLabel();
        LabelnoTelp2 = new javax.swing.JLabel();
        LabelKelamin2 = new javax.swing.JLabel();
        buttonCowo = new javax.swing.JRadioButton();
        buttonCewe = new javax.swing.JRadioButton();
        TextFieldnoTelp = new javax.swing.JTextField();
        TextFieldAlamat = new javax.swing.JTextField();
        TextFieldNama = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        namaEmpty = new javax.swing.JLabel();
        alamatEmpty = new javax.swing.JLabel();
        noTelpEmpty = new javax.swing.JLabel();
        jenisKelaminEmpty = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(23, 23, 23));

        LabelTambahDataPelanggan2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LabelTambahDataPelanggan2.setForeground(new java.awt.Color(255, 255, 255));
        LabelTambahDataPelanggan2.setText("Tambah Data Pelanggan");

        LabelNama2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelNama2.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama2.setText("Nama");

        LabelAlamat2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelAlamat2.setForeground(new java.awt.Color(255, 255, 255));
        LabelAlamat2.setText("Alamat");

        LabelnoTelp2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelnoTelp2.setForeground(new java.awt.Color(255, 255, 255));
        LabelnoTelp2.setText("no. Telp");

        LabelKelamin2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelKelamin2.setForeground(new java.awt.Color(255, 255, 255));
        LabelKelamin2.setText("Jenis Kelamin");

        buttonCowo.setBackground(new java.awt.Color(23, 23, 23));
        groupKelamin.add(buttonCowo);
        buttonCowo.setForeground(new java.awt.Color(255, 255, 255));
        buttonCowo.setText("Laki-Laki");

        buttonCewe.setBackground(new java.awt.Color(23, 23, 23));
        groupKelamin.add(buttonCewe);
        buttonCewe.setForeground(new java.awt.Color(255, 255, 255));
        buttonCewe.setText("Perempuan");

        TextFieldnoTelp.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldnoTelp.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldnoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnoTelpActionPerformed(evt);
            }
        });

        TextFieldAlamat.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldAlamat.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAlamatActionPerformed(evt);
            }
        });

        TextFieldNama.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldNama.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(48, 48, 48));
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonKembali.setBackground(new java.awt.Color(48, 48, 48));
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("Kembali");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        namaEmpty.setForeground(new java.awt.Color(255, 255, 255));

        alamatEmpty.setForeground(new java.awt.Color(255, 255, 255));

        noTelpEmpty.setForeground(new java.awt.Color(255, 255, 255));

        jenisKelaminEmpty.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LabelTambahDataPelanggan2)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jenisKelaminEmpty)
                                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(LabelKelamin2)
                                    .addGap(100, 100, 100)
                                    .addComponent(buttonCowo)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonCewe)))
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelNama2)
                                .addComponent(LabelAlamat2)
                                .addComponent(LabelnoTelp2))
                            .addGap(113, 113, 113)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(namaEmpty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldNama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alamatEmpty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(noTelpEmpty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldnoTelp))
                            .addContainerGap()))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTambahDataPelanggan2)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama2))
                .addGap(3, 3, 3)
                .addComponent(namaEmpty)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlamat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatEmpty)
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldnoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelnoTelp2))
                .addGap(1, 1, 1)
                .addComponent(noTelpEmpty)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCowo)
                            .addComponent(buttonCewe)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelKelamin2)))
                .addGap(1, 1, 1)
                .addComponent(jenisKelaminEmpty)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldnoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnoTelpActionPerformed

    private void TextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAlamatActionPerformed

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        Home H = new Home();
        setVisible(false);
        H.setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String namaPelanggan = TextFieldNama.getText();
        String alamatPelanggan = TextFieldAlamat.getText();
        String notelpPelanggan = TextFieldnoTelp.getText();
        
        String jeniskelamin = "";
        try { //try catch jenisKelamin
            if (groupKelamin.getSelection().equals(buttonCowo.getModel())) {
                jeniskelamin = "Laki-Laki";
            } else if (groupKelamin.getSelection().equals(buttonCewe.getModel())) {
                jeniskelamin = "Perempuan";
            }
        } catch (NullPointerException e) {
            jenisKelaminEmpty.setText("Please select one of two");
        }
        if (!jeniskelamin.equals("")){
            jenisKelaminEmpty.setText("");
        }

        //kalau text field masing-masing kosong
        if (namaPelanggan.equals("")){
            namaEmpty.setText("This field is required");
        }else if(!namaPelanggan.equals("")){
            namaEmpty.setText("");
        }
        if (alamatPelanggan.equals("")){
            alamatEmpty.setText("This field is required");
        }else if (!alamatPelanggan.equals("")){
            alamatEmpty.setText("");
        }
        if (notelpPelanggan.equals("")){
            noTelpEmpty.setText("This field is required");
        }else if (!notelpPelanggan.equals("")){
            noTelpEmpty.setText("");
        }
        
        if(!namaPelanggan.equals("")&&!alamatPelanggan.equals("")&&
                !notelpPelanggan.equals("")&&!jeniskelamin.equals("")){
            try{
                CustomerController customerController = new CustomerController();
                customerController.insertPerson(namaPelanggan, alamatPelanggan, notelpPelanggan, jeniskelamin);
                Home H = new Home();
                setVisible(false);
                H.setVisible(true);
                JOptionPane.showMessageDialog(null, "Data Pelanggan berhasil disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Penambahan data pelanggan gagal");
            }
        }
        
        
    }//GEN-LAST:event_buttonSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAlamat2;
    private javax.swing.JLabel LabelKelamin2;
    private javax.swing.JLabel LabelNama2;
    private javax.swing.JLabel LabelTambahDataPelanggan2;
    private javax.swing.JLabel LabelnoTelp2;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldnoTelp;
    private javax.swing.JLabel alamatEmpty;
    private javax.swing.JRadioButton buttonCewe;
    private javax.swing.JRadioButton buttonCowo;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.ButtonGroup groupKelamin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jenisKelaminEmpty;
    private javax.swing.JLabel namaEmpty;
    private javax.swing.JLabel noTelpEmpty;
    // End of variables declaration//GEN-END:variables
}
